/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proxyfetcher;

import proxyfetcher.websiteClasses.advancedName;

public class App {

    public static void main(String[] args) {
        advancedName myObject = new advancedName();

        myObject.fetchProxies().forEach((strProxy) -> {
            System.out.println(strProxy);
        });
    }
}
