/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proxyfetcher;

import proxyfetcher.websiteClasses.advancedName;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);


        
        //System.out.println(objAdvance.fetchRandomProxy().serveAddress());

        /*objAdvance.fetchProxies().forEach((objProxy) -> {
            System.out.println(objProxy.serveAddress());
        });*/
    }
}
